### ISSUE TITLE
Crash when chest inoperable

### ISSUE THREAD

**Issue by Heaveline-Helios** [Skylortrexler/MiniMiner#1]
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/30/22, 3:41 AM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1263.method_5439()" because "chestInventory" is null
	at website.skylorbeck.miniminer.entity.MiniMinerBlockEntity.tick(MiniMinerBlockEntity.java:161)
	at net.minecraft.class_2818$class_5563.redirect$bag000$checkProcessTEs(class_2818.java:783)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.redirect$bhh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3790)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.handler$bad000$modifiedRunLoop(MinecraftServer.java:2896)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at website.skylorbeck.miniminer.entity.MiniMinerBlockEntity.tick(MiniMinerBlockEntity.java:161)
	at net.minecraft.class_2818$class_5563.redirect$bag000$checkProcessTEs(class_2818.java:783)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.redirect$bhh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3790)

-- Block entity being ticked --
Details:
	Name: miniminer:miniminer_entity // website.skylorbeck.miniminer.entity.MiniMinerBlockEntity
	Block: Block{miniminer:miniminerblock}
	Block location: World: (564,88,-409), Section: (at 4,8,7 in 35,5,-26; chunk contains blocks 560,-64,-416 to 575,319,-401), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Block: Block{miniminer:miniminerblock}
	Block location: World: (564,88,-409), Section: (at 4,8,7 in 35,5,-26; chunk contains blocks 560,-64,-416 to 575,319,-401), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.redirect$bhh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3790)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.handler$bad000$modifiedRunLoop(MinecraftServer.java:2896)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Unknown Source)

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

Fabric Mods: 
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		ae2: Applied Energistics 2 11.0.0-alpha.5
		ae2wtlib: AE2WTLib 11.0.0-alpha.2
		alternate-current: Alternate Current 1.2.0
		apoli: Apoli 2.3.3
		architectury: Architectury 4.2.50
		autoconfig1u: Auto Config v1 Updated 3.4.0
		autosmeltenchant: AutosmeltEnchant 1.1.0
		beaconoverhaul: Beacon Overhaul 1.6.0+1.18.2
		bewitchment: Bewitchment 1.18-17
		blue_endless_jankson: jankson 1.2.1
		bookshelf: Bookshelf 13.0.13
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
		calio: Calio 1.5.1
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carpet: Carpet Mod 1.4.69
		carpet-extra: Carpet Extra 1.4.72
		carpet-tis-addition: Carpet TIS Addition 1.33.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.0+8
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_ishland_c2me_libs_: libs 0.2.0+alpha.7.0
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		conditional-mixin: conditional mixin 0.2.0
		cooldown-coordinator: Cooldown Coordinator 0.3.0
		dark-enchanting: Dark Enchanting 0.7.0+1.18.2
		dcintegration-fabric: Discord Integration Fabric 2.3.6
		de_erdbeerbaerlp_discordintegration-core: DiscordIntegration-Core ce44c82e
		decorative_blocks: Decorative Blocks 2.1.0
		eldritch_mobs: Eldritch Mobs 1.11.0
		enderchests: EnderChests 1.0.9
		enhanced_quarries: Enhanced Quarries 1.18.2-1.2.1
		expandedstorage: Expanded Storage 7.3.12
		extragenerators: Extra Generators 1.2.1-BETA+1.18
		extraorigins: Extra Origins 1.18-10
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		farsight: Farsight Mod 1.18-1.8
		fiber: fiber 0.23.0-2
		friendlyfire: FriendlyFire 11.0.2
		geckolib3: Geckolib 3.0.38
		grindenchantments: Grind Enchantments 1.6.3+1.18.2
		impersonate: Impersonate 2.4.1
		inmis: Inmis 2.5.3-1.18.2
		inventorysorter: Inventory Sorter 1.8.6-1.18
		invview: InvView 1.4.8-1.18+
		iron-jetpacks: Iron Jetpacks 0.4.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.2.0+1.14.4-1.19
		krypton: Krypton 0.1.9
		ksyxis: Ksyxis 1.1
		kyrptconfig: Kyrpt Config 1.4.2-1.18
		libblockattributes: LibBlockAttributes 0.10.2
		libblockattributes_core: LibBlockAttributes (Core) 0.10.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.2
		libblockattributes_items: LibBlockAttributes (Items) 0.10.2
		libgui: LibGui 5.3.2+1.18.2
		libninepatch: LibNinePatch 1.1.0
		lightestlamp: Lightest Lamps 1.0.0
		lithium: Lithium 0.7.9
		minecraft: Minecraft 1.18.2
		miniminer: Miniminer 1.0.0
		moborigins: Mob Origins 1.8.1
		myron: Myron 1.6.3+1.18.1
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.3-1.18.1
		omnihopper: Omni-Hopper 1.1.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_yaml_snakeyaml: snakeyaml 1.30
		origins: Origins 1.4.1
		origins-classes: Origins: Classes 1.3.0
		patchouli: Patchouli 1.18.2-67-FABRIC
		pehkui: Pehkui 3.2.2+1.14.4-1.19
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player_events: Player Events 2.2.4
		player_events_api: Player Events API 2.2.4
		playerabilitylib: Pal 1.5.0
		polymorph: Polymorph 0.0.20-1.18.2
		publicguiannouncement: Public Gui Announcement 3.2.0.1
		pugh_tools: Pugh Tools 1.2.5
		quartzelv: Quartz Elevator 2.1.1+1.18
		quickhomes: QuickHomes 1.18.2-1.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.2.0-beta.3
		right-click-harvest: Right-Click-Harvest 1.2.0
		ring_of_attraction: Ring Of Attraction 1.2.24
		ring_of_enderchest: Ring of Enderchest 1.2.23
		ring_of_growth: Ring Of Growth 1.2.23
		ring_of_miner: Ring Of Miner 1.3.26
		ring_of_teleport: Ring Of Teleport 1.1.24
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 8.1.457
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shetiphiancore: ShetiPhianCore 1.2.10
		simplegrinder: Simple Grinder 18_2.0.2
		skylorlib: SkyLib 1.3.34
		smoothchunk: Smooth chunk save Mod 1.18.2-1.8
		spark: spark 1.9.1
		stackablepotions: Stackable Potions 1.0.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structures_compass: Structures Compass 1.18.2-1.4.2
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.2.0-beta.3
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		toofast: TooFast 0.0.2.3
		totemmod: Wither Totems Mod 0.3.5-1.18.2-pre2
		trinkets: Trinkets 3.3.0
		veinmining: Vein Mining 0.0.12-1.18.2
		voicechat: Simple Voice Chat 1.18.2-2.2.37
		wands: Building Wands 2.4.1_mc1.18.2
		waystones: Waystones 2.5.0
		worldedit: WorldEdit 7.2.10+1742f98

**Comment by skylorbeck** [comment]
Dude I never even got a notification about this being opened. Rad.

**Comment by Heaveline-Helios** [comment]
Lol, still fixed it so props to you for the good work! xD
